ApiDoctor.Publishing/CSDL/csdlextensionmethods.cs, ApiDoctor.Publishing/CSDL/csdlwriter.cs, ApiDoctor.Validation/OData/Action.cs, ApiDoctor.Validation/OData/ComplexType.cs, ApiDoctor.Validation/OData/Parameter.cs, ApiDoctor.Validation/OData/Property.cs, ApiDoctor.Validation/OData/ReturnType.cs
We found that there were attributes being stripped or being added when they shouldn't be. This fix addresses those issues. Additionally, I changed the order of properties to maintain the input order per what appears to be Graph standard. More notes in the commits. 
`publish-edmx --path D:\repos\docs\api-reference\v1.0 --source D:\metadata\2018_09_14\v1.0_2018_09_14_source_clean.xml --output finalmetadata2 --skip-generation`
=> Fix attributes

ApiDoctor.Console/Program.cs
ApiDoctor does not respect the --ignore-warnings flag. 
We need to respect this flag since we have the new "treatErrorsAsWarnings" section that allows us to treat errors in certain workloads as warnings.
=> Respect Ignore warnings flag.

ApiDoctor.Validation/Json/JsonSchema.cs, ApiDoctor.Validation/ParameterDataType.cs
Nested Json objects, where there is an array inside an array cause type mismatch errors. This PR fixes this bug by turning nested collections into a JsonCollection that is assumed to be an object. 
`
{
"values" : [["Hello", "100"],["1/1/2016", null]],
"formula" : [[null, null], [null, "=B1*2"]],
"numberFormat" : [[null,null], ["m-ddd", null]]
}
`
=> Support nested Json collections.

ApiDoctor.Validation.UnitTests/BrokenLinkTests.cs, ApiDoctor.Validation/DocFile.cs, ApiDoctor.Validation/Error/validationerror.cs
All Urls should be in lowercase. 
so we don't have 
"GET-USER.md"
we have
"get-user.md"
Includes test to verify this.
=> Validation Rule: Enforce lowercase file names in urls

ApiDoctor.Validation/Tags/TagProcessor.cs
This PR involves the addition of support for the docfx tab headers which have link targets that are in the fashion of `#tab/{tabid}` or `#tab/{tabid}/{condition}`.
=> Add support for docfx tab headers

ApiDoctor.Console/ApiDoctor.ConsoleApp.csproj, ApiDoctor.Console/Program.cs, ApiDoctor.Console/packages.config, ApiDoctor.DocumentationGeneration/ApiDoctor.DocumentationGeneration.csproj, ApiDoctor.Publishing/ApiDoctor.Publishing.csproj, ApiDoctor.Validation.UnitTests/ApiDoctor.Validation.UnitTests.csproj, ApiDoctor.Validation/ApiDoctor.Validation.csproj, ApiDoctor.Validation/Config/MetadataValidationConfigFile.cs, ApiDoctor.Validation/DocSet.cs, ApiDoctor.Validation/Json/JsonSchema.cs, ApiDoctor.Validation/Json/ValidationOptions.cs, ApiDoctor.Validation/Json/jsonresourcecollection.cs, ApiDoctor.Validation/OData/ODataParser.cs
- Cleaned up and Enhanced "CheckMetadataOptions" Route to support multiple useful scenarios, and a world where not everything is perfect aka documented.
- There shouldn't be any breaking changes to the current flow of the route. There was a minor change to the flow in (ApiDoctor.Validation/Json/jsonresourcecollection.cs) where it seemed to be either a bug/typo or poor design to always overwrite options.
=> Validate Docs against Metadata Route

ApiDoctor.Validation/DocFile.cs, ApiDoctor.Validation/ParameterDefinition.cs
Infer namespace from resource to remove need for specifying namespace in page annotation for resource topics
Validate object property types against resource names
=> Infer namespace from resource

ApiDoctor.Console/ApiDoctor.ConsoleApp.csproj, ApiDoctor.Console/CommandLineOptions.cs, ApiDoctor.Console/GitHelper.cs, ApiDoctor.Console/Program.cs, ApiDoctor.Validation/Http/HttpParser.cs, ApiDoctor.Validation/MethodDefinition.cs
HTTP parsing and injection logic is implemented by @andrueastman.
On top of that infrastructure, I have some changes for the generation logic to use a command line tool instead of HTTP calls.
I can't set two assignees for some reason in this repo, so consider myself and Andrew as assignees.
The whole logic should be running in a separate path than what is already in apidoctor through a new command line parameter (`generate-snippets`). Please review if any shared code changes could potentially cause problems for other functionalities.
cc: @baywet (can't mark as reviewer as you are not part of the org)
=> Merging snippet generation logic into OneDrive/apidoctor

ApiDoctor.Validation/DocSet.cs, ApiDoctor.Validation/Error/validationerror.cs
There have been issues with code snippet generation where baseType in resource topic is empty. 
This PR aims to ensure that a validation error is thrown when an empty baseType is encountered.
=> Base type should not be empty

ApiDoctor.Publishing/CSDL/csdlextensionmethods.cs
**Problem**
If we had a request definition like this, `https://graph.microsoft.com/beta/identityGovernance/accessReviews/historyDefinitions/b2cb022f-b7e1-40f3-9854-c65a40861c38/generateDownloadUri()`, API doctor will throw the below error which isn't very helpful.
```Error:  Malformed function params```
**Fix**
Add method name to error message to help users locate the error.
Add information to the user on how to fix the problem
```
Error: accessreviewhistorydefinition_generatedownloaduri:
Malformed function params '. Expected key-value params e.g. function1(key=value). Remove paranthesis if no params are expected.
```
=> Add more information in error message when function call does not have key-value params

ApiDoctor.Validation/Json/JsonSchema.cs
**Bug**
API Doctor crashes if request/response body is whitespace
**Fix**
Report an error if an attempt to validate a json string that is empty or white space
Not expected to break any docs validation.
=> Ensure JSON request or response body is not whitespace

ApiDoctor.Validation/ApiDoctor.Validation.csproj, ApiDoctor.Validation/Http/HttpParser.cs, ApiDoctor.Validation/ObjectGraph/objectgraphmerger.cs
[Microsoft.AspNetCore.WebUtilities](https://www.nuget.org/packages/Microsoft.AspNetCore.WebUtilities) has been [deprecated since 2018](https://github.com/aspnet/HttpAbstractions) and it depends on a version of [System.Text.Encodings.Web](https://www.nuget.org/packages/System.Text.Encodings.Web/4.5.0) that's vunlerable to CVE-2021-26701.
Since we were only using that library to parse query string parameters, I've replaced it by the [System.Web.HttpUtility.ParseQueryString method](https://docs.microsoft.com/en-us/dotnet/api/system.web.httputility.parsequerystring?view=netframework-4.5) instead.
=> removes reference to deprecated and vulnerable Microsoft.AspNetCore.WebUtilities

ApiDoctor.Validation/Json/JsonSchema.cs, ApiDoctor.Validation/ResourceDefinition.cs
Newtonsoft.Json 13.0.1, changed the default MaxDepth for JsonReader to 64, and it caused a breaking change.
A legacy API surprisingly had one resource that's over the default limit. (I'm following up to clean it as well)
=> Update JsonReader and JsonSerializer MaxDepth

ApiDoctor.Publishing/CSDL/csdlextensionmethods.cs, ApiDoctor.Publishing/CSDL/csdlwriter.cs, ApiDoctor.Validation.UnitTests/DocFileForTesting.cs, ApiDoctor.Validation/DocFile.cs, ApiDoctor.Validation/Error/validationerror.cs, ApiDoctor.Validation/MethodDefinition.cs, ApiDoctor.Validation/OData/EntitySet.cs, ApiDoctor.Validation/OData/ISet.cs, ApiDoctor.Validation/OData/Singleton.cs, ApiDoctor.Validation/OData/Term.cs, ApiDoctor.Validation/Params/CSharpEval.cs, ApiDoctor.Validation/SupplementalFile.cs, ApiDoctor.Validation/Tags/TagProcessor.cs
***Blocking Bugs***
Initial implementation blocked by a bug where APiDoctor mishandles YAML Front Matter, thereby misunderstanding the whole document model and breaking downstream csdl handling logic. 
***Features***
Extract Operation titles and descriptions and inject them into generated csdl as `*Restrictions` (Read, ReadByKey).
For  the example above:-
- Extract corresponding page title as `Description`
- Extract corresponding page first paragraph as `LongDescription`
These injected `*Restrictions` will be extracted by [OpenAPI.NET.Odata](https://github.com/microsoft/OpenAPI.NET.OData/pull/206) and inserted into generated OpenAPI files as summaries and descriptions.
These summaries and descriptions will then flow into the Microsoft Graph PowerShell SDK Docs which extract the summaries …
=> Add feature to inject documentation annotations as *Restrictions into Metadata

ApiDoctor.Publishing/CSDL/csdlwriter.cs, ApiDoctor.Validation/DocFile.cs, ApiDoctor.Validation/ExtensionMethods.cs
This is to remove markdown links from description annotations.
Some methods had wrong descriptions because the description was being fetched from methods in conceptual pages but what we are interested in is descriptions in API pages.
=> Fix CSDL publishing

ApiDoctor.Console/Program.cs, ApiDoctor.Validation/ExtensionMethods.cs
Updates in this PR:
- Get snippets language set for document
- Ensure all methods in the document have tabs for all languages in the set
- Methods that do not have a snippet for a particular language have the information `Snippet not available` within the tab
- Removes HTTP tab if there's no snippets available in other languages
- Only adds missing tabs if method has at least one code snippet in a programming language
Docs PR with generated snippets with these changes: https://github.com/microsoftgraph/microsoft-graph-docs/pull/17711
Docs [example](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17711&tabs=java#example-7-use-search-to-get-users-with-display-names-that-contain-the-letters-wa-or-the-letters-ad-including-a-count-of-returned-obje …
=> Add tabs for missing snippets

ApiDoctor.Console/CommandLineOptions.cs, ApiDoctor.Console/Program.cs, ApiDoctor.Validation/Error/validationerror.cs
- Adds a new command line option to deduplicate example names, which is supposed to be unique within a version (beta, v1).
The logic goes:
- Parses the entire documentation and detects duplicates
- Appends a counter at the end of the duplicate name
- This sometimes collides with existing names, so makes sure that counter is incremented further if the proposed name still collides (e.g. deduping `get-user`, but there is already a `get-user-1`, so it reattempts with `get-user-2`).
- Reruns the duplicate check after all the replacements are done to make sure that the detection and replacement logic doesn't have a bug and generates a desired outcome (no duplicates)
- If this fails, it is reported as an error so that it can be fixed in APIDoctor.
The idea is to run this command line option …
=> add deduplicate-example-names command line option

ApiDoctor.Console/Program.cs
Validation by ApiDoctor fails if the embedded link contains `$` characters in them as witnessed in https://github.com/microsoftgraph/microsoft-graph-docs/pull/17920
This PR adds the `$` character to the cleanup regex to avoid this scenario in future.
=> Strip `$` characters from generated snippet files

ApiDoctor.Publishing/CSDL/csdlwriter.cs
This PR addresses potential NullReference exceptions discovered in the latest weekly generation of the SDKs.
Changes include:
- Adding checks to returned values from `FirstOrDefault()` to check if the value is a default
- Add defensive programming checks in the `AddLinkAnnotation` function
=> Fix NullReference exceptions from latest generation

ApiDoctor.Validation/OData/IODataNavigable.cs
This PR addresses a bug where the `IODataNavigable.cs` would indescriminately overrride the `IsComposable` property for functions to lead to incorrect transformed metadata.
This PR applies a change to apply this condition if the Function exists in a part of the URL that is not the last segment meaning it would have to be composable for the URL to continue being built.
=> Fix for setting IsComposable to true

ApiDoctor.Console/ApiDoctor.ConsoleApp.csproj, ApiDoctor.Console/Program.cs
This PR
- Updates boilerplate text for permissions only if we have a new table from Kibali during the bootstrapping process
- Adds YAML header to autogenerated permissions file
- Bumps Kibali version to 0.7.0
=> Update Kibali version to 0.7.0

ApiDoctor.Console/CommandLineOptions.cs, ApiDoctor.Console/Program.cs
- fixes https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/1700
- partial https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/595
- adds temp-output-path as the temporary snippets output path
- removes the step that deletes the temp folder to allow further analysis of failures
- whenever there is a naming collision, it writes a duplicate file in the format:
- `normalized-snippet-name-<version>-httpSnippet-duplicate<duplicateCount>`
- in later pipelines, these outputs will be parsed for failure analysis.
=> - adds a new command line param temp-output-path

ApiDoctor.Validation/DocFile.cs, ApiDoctor.Validation/Error/validationerror.cs
Fixes #185 
This PR adds validation of code snippets tab section. by performing the following checks:
- No duplicated tabs
- Existence of tab boundary at the end of tab group definition
- Tab groups have the same tabs
- At least two tabs in a tab group
- HTTP tab should be present
- Tabs should only be within the example request sections
=> Validate tab section within examples requests

ApiDoctor.Console/Program.cs
This PR fixes a regression that would prevent snippet block parsing due to failed version lookup as previous versions of APIDoctor would do a best-effort attempt to obtain version for the snippets during generation.
If the version cannot be obtained from the URL, the version is inferred from the file location and a warning will continue to be logged as before for action from the documentation to fixed.
Sample generation at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=112494&view=results
Related to https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1477
=> Fixes snippet version parsing.

ApiDoctor.Console/Constants.cs, ApiDoctor.Console/Program.cs, ApiDoctor.Validation/OData/Transformation/SchemaConfigFile.cs
This PR
- Removes the need to replace only specific permissions table boilerplate text but replaces all. We're doing this because we've already established that all current texts should be replaced.
- Add ignored permissions tables to tally of found tables so that we can correctly map requests to tables
- Automatically skips update of permission files with asterisks and superscript because otherwise, important information would be overwritten.
- Automatically skips update of permissions files with keyword specified in config file of docs
=> Update permissions table generation

ApiDoctor.Console/Program.cs, ApiDoctor.Publishing/CSDL/csdlextensionmethods.cs
Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1811
=> Report error if base URL in example request is not in config

ApiDoctor.Publishing/CSDL/csdlextensionmethods.cs
Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1812
=> Properly validate functions that accept a collection of function parameter values

ApiDoctor.Validation/DocFile.cs, ApiDoctor.Validation/DocSet.cs
In this PR:
- Change warnings to errors if properties table + JSON representation don't match
- No error if property is defined in baseType
=> Elevate API Doctor warnings to blocking errors if properties table + JSON representation don't match

ApiDoctor.Validation/ExtensionMethods.cs, ApiDoctor.Validation/OData/ExtensionMethods.cs, ApiDoctor.Validation/ParameterDataType.cs, ApiDoctor.Validation/ParameterDefinition.cs
Fixes #186 
Process Edm.Decimal as Edm.Double since they will look the same in the examples
=> Add support for processing Edm.Decimal data type

ApiDoctor.Validation/CodeBlockAnnotation.cs, ApiDoctor.Validation/DocSet.cs
Properties for open types are dynamic
=> Skip validation of JSON properties against markdown table if resource is open type

ApiDoctor.Validation/DocFile.cs, ApiDoctor.Validation/DocSet.cs, ApiDoctor.Validation/OData/Transformation/SchemaConfigFile.cs
Some property names have text such as `(deprecated)` appended to them. The change in this PR will strip the additional text before validation.
=> Remove additional text from property names before validation

ApiDoctor.Console/Program.cs, ApiDoctor.Validation.UnitTests/YamlParserTests.cs, ApiDoctor.Validation/CodeBlockAnnotation.cs, ApiDoctor.Validation/DocFile.cs
Closes #280
This PR:
- Logs when a set of URLs do not have the same set of permissions
- Logs when the number of HTTP request blocks are more than the number of permissions tables
- Processes new properties in the permissions HTML comment metadata, namely: `requestUrls` and `mergePermissions`
=> Implement conditional update of permissions tables based on HTML comment command

ApiDoctor.Console/Program.cs
This PR
- Makes sure that we capture different formatting of the HTML comment metadata preceding the permissions table
- Adds missing HTML comment metadata to 'included' permissions table
- Handles exceptions thrown when attempting to deserialize JSON data in the HTML comment metadata
- Simplifies how we compute where to start looking for the next permissions table after finding the first one
=> Updates to permissions tables generation

ApiDoctor.Console/Constants.cs, ApiDoctor.Console/Program.cs
The documentation team has begun manually creating permissions tables and adding metadata to guide API Doctor in populating these tables through Kibali. Initially, we assumed that non-bootstrapped tables lacked the HTML comment metadata. This PR ensures that the metadata is processed correctly
=> Account for 'non-bootstraped' permissions tables that have HTML comment metadata

ApiDoctor.Console/Program.cs
This is to help in identifying request blocks that do not have the same set of permissions for action by the content team
=> Do not emit errors in the console when comparing null permissions tables for request URLs within the same HTTP request block
